version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./dockerfiles/node/Dockerfile
    container_name: node_app
    ports:
      - '3000:3000'
      - '9229:9229'
    env_file: .env
    volumes:
      - .:/home/app
      - /home/app/node_modules
    tty: true
    depends_on:
      - mysql
    networks:
      - mynetwork

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: me
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: sso_db
    volumes:
      - ./db_data/mysql:/var/lib/mysql
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
